// Alle Afrikaanse teks vir Stapel. Keep every player-facing string here, and its English twin in
// js/core/strings.en.js (same keys and shapes; tests/i18n.test.js checks). js/core/i18n.js swaps the
// tables in place, so code keeps reading S.x as always. Use the typographic ’n (U+2019).

export const S = {
  title: 'Stapel',
  tagline: 'Stapel hoog. Staan sterk.',
  loading: 'Laai…',
  rotate: 'Draai jou foon regop om te speel.',

  // --- Tuisskerm (menu) ---
  daily: 'Daaglikse Toring',
  dailyN: (n) => `Daaglikse Toring #${n}`,
  playToday: 'Bou vandag se toring',
  doneToday: 'Klaar vir vandag!',
  seeResult: 'Kyk na jou uitslag',
  nextTower: 'Volgende toring oor',
  practice: 'Oefen',
  practiceSub: 'Speel soveel jy wil — dit tel nie',
  howTo: 'Hoe speel ek?',
  howToShort: 'Speelreëls',           // the menu's bottom row (one line under its icon)
  stats: 'Statistiek',
  settings: 'Instellings',
  sound: 'Klank',
  vibration: 'Vibrasie',
  on: 'Aan',
  off: 'Af',
  close: 'Maak toe',
  back: 'Terug',
  forecast: 'Vandag se weervoorspelling',
  sameForAll: 'Dieselfde blokke en weer vir almal. Een poging.',
  oneTry: 'een poging, dieselfde vir almal',   // (1.12) on the daily card's date line
  todayLabel: 'Vandag:',                        // (1.12) before the day's weather and visitors on the menu
  unfinished: 'Jou vorige poging is onderbreek, maar dit tel soos dit was.',
  newDay: '’n Nuwe toring wag!',

  // --- In die spel (in game) ---
  tapToDrop: 'Tik om te laat val',
  perfect: 'Perfek!',
  perfectCombo: (n) => `Perfek ×${n}!`,
  good: 'Goed',
  skew: 'Skeef',
  lost: 'Oeps!',
  extraLife: '’n Lewe terug!',
  height: 'Hoogte',
  points: 'Punte',
  lives: 'Lewens',
  next: 'Volgende',
  combo: 'Kombo',
  wobble: 'Wankel',
  waterBelow: (m) => `🌊 Vloedlyn ${m} onder`,
  waterRising: 'Die water styg!',
  waterDanger: 'Bou vinniger — die water kom!',
  waterRecede: 'Die water sak!',
  practiceLabel: 'Oefenrondte',
  blocksLeft: (n) => (n === 1 ? 'nog 1 blok' : `nog ${n} blokke`),

  // --- Pouse (pause) ---
  paused: 'Gepouseer',
  resume: 'Speel verder',
  quit: 'Hou op',
  quitWarnDaily: 'As jy nou ophou, tel hierdie poging as jou Daaglikse Toring.',
  pause: 'Pouseer',

  // --- Uitslag (results) ---
  results: 'Uitslag',
  overLives: 'Jou lewens is op!',
  overLivesSub: 'Te veel blokke het in die see geplons.',
  overFlood: 'Oorstroom!',
  overFloodSub: 'Die water het jou toring ingehaal.',
  overQuit: 'Bouwerk gestaak',
  overQuitSub: 'Jy het die hyskraan afgeskakel.',
  blocks: 'Blokke',
  perfects: 'Perfek',
  bestCombo: 'Beste kombo',
  duration: 'Tyd',
  share: 'Deel',
  shareWhatsApp: 'Deel op WhatsApp',
  copy: 'Kopieer',
  copied: 'Gekopieer!',
  copyFailed: 'Kon nie kopieer nie',
  shared: 'Gedeel!',
  home: 'Tuis',
  practiceAgain: 'Oefen weer',
  newRecord: 'Nuwe rekord!',
  weatherToday: 'Weer',

  // --- Statistiek ---
  played: 'Gespeel',
  currentStreak: 'Huidige reeks',
  maxStreak: 'Langste reeks',
  bestHeight: 'Hoogste toring',
  bestScore: 'Meeste punte',
  totalPerfects: 'Perfekte blokke',
  lastWeek: 'Die afgelope 7 dae',
  noGamesYet: 'Nog geen Daaglikse Torings gebou nie.',

  // --- Hoe speel ek? ---
  howToTitle: 'Hoe speel ek?',
  howToSteps: [
    // (1.12: half the words, one line each; testers found the long version "too AI generated")
    { icon: '👆', text: 'Tik om die blok te laat val. Die wit vorm wys waar dit land.' },
    { icon: '🎯', text: 'Land in die middel vir ’n Perfek. Perfeks op ’n ry gee ekstra punte.' },
    { icon: '🧱', text: 'Onder word die toring sement; bo bly dit los. Die Balans-meter wys hoe naby die bokant aan omval is.' },
    { icon: '🌦️', text: 'Hoe hoër jy bou, hoe meer weer: wind, reën, weerlig, hael en mis.' },
    { icon: '🌊', text: 'Die water styg. Hou jou toring bo die vloedlyn.' },
    { icon: '❤️', text: 'Drie lewens. ’n Blok in die see kos een, elke vierde Perfek bring een terug.' },
    { icon: '🐒', text: 'Besoekers: ’n Perfek jaag Blouaap weg, tik Skelm Sakkie vas, en Hanswors bring geskenke. Hulle kos nooit ’n lewe nie.' },
    { icon: '🗓️', text: 'Een Daaglikse Toring per dag: dieselfde vir almal, een poging. Oefen soveel jy wil.' },
  ],
  // the short lesson (1.10): a new player's first Oefen game, step by step
  lessonTry: 'Probeer die kort les',
  lesson1: 'Tik enige plek om die blok te laat val.',
  lesson2: 'Mik vir die middel. Die wit vorm wys waar die blok gaan land.',
  lesson3: 'Perfek! Vyf op ’n ry bring Hanswors met geskenke.',
  lesson3b: 'Amper. Hoe nader aan die middel, hoe meer punte.',
  lesson4: 'Die water styg. ’n Blok in die see kos ’n lewe.',
  lessonDone: 'Jy is reg. Elke dag is daar een Daaglikse Toring: dieselfde blokke vir almal, en een kans.',
  lessonDaily: 'Speel vandag se toring',
  lessonMore: 'Oefen verder',
  lessonSkip: 'Slaan oor',
  howToGo: 'Kom ons bou!',
  privacyPolicy: 'Privaatheidsbeleid',

  // --- Deel-teks (share text; core/share.js) ---
  shareDailyHead: (n) => `Stapel #${n}`,
  sharePracticeHead: 'Stapel (oefenrondte)',

  // --- Eerste speletjie: leidrade tydens die spel (js/core/coach.js) ---
  firstNudge: 'Nuut? Tik net en speel — ons wys jou hoe.',
  sayingOfDay: 'Spreekwoord van die dag',
  coachTap: 'Tik om te laat val 👆',
  coachMiddle: 'Mik vir die middel — die wit vorm wys waar dit land',
  coachPerfect: 'Perfek! Doen dit weer 🎯',
  coachWater: 'Die water styg — bou vinniger as die vloedlyn 🌊',
  coachLost: '’n Blok in die see kos ’n hartjie ❤️',

  // --- Bygevoeg in 1.0.1 ---
  ghostHint: 'Hier land jou blok',
  clickToDrop: 'Klik of druk spasie om te laat val',
  nextTowerCaption: 'tot die volgende toring',
  newTowerGo: 'Bou die nuwe toring',
  lostCount: 'Verlore',
  notPlayed: 'nie gespeel nie',
  nothingToShare: 'Niks om te deel nie — probeer weer!',
  otherTab: 'Jy bou reeds in ’n ander oortjie.',
  reloadNeeded: 'Die skerm het gevries. Laai die bladsy weer as dit nie regkom nie.',
  highContrast: 'Kontras',
  peek: 'Toring',
  peekBack: 'Uitslag',
  wobbleTitle: 'Balans',

  // --- Borge (sponsors) ---
  adLabel: 'Advertensie',
  adOpens: 'maak in ’n nuwe oortjie oop',
  advertiseHere: 'Adverteer hier',
  boardFree: 'Jou advertensie hier!',
  boardFreeSub: 'Adverteer op Stapel',
  // results card: how today's tower compares with the other players (never in the WhatsApp text)
  percentileBetter: (n) => `Jy het beter gedoen as ${n}% van spelers vandag`,
  // "Jou Stapelstad": every finished Daaglikse Toring becomes a building in the player's own skyline
  cityTitle: 'Jou Stapelstad',
  cityLine: (n) => (n === 1 ? 'Jou stad se eerste toring staan!' : `Jou stad het nou ${n} torings!`),
  cityStreak: (n) => (n >= 2 ? `${n} dae in ’n ry` : ''),
  cityBest: 'Beste toring',
  cityEmpty: 'Voltooi ’n Daaglikse Toring om jou stad te begin bou.',
  cityAria: (n, days) => `Jou Stapelstad: ${n} torings in die laaste ${days} dae`,
  // friend challenge (?klop=<dm>&d=<date>)
  challengeMenu: (m) => `’n Vriend daag jou uit: klop ${m}! 🚩`,
  challengeLine: (m) => `Klop dié: ${m}`,
  challengeWon: 'Jy het jou vriend geklop! 🎉',
  // tomorrow teaser on the daily results
  tomorrow: 'Môre',
  tomorrowLine: (emoji) => `Môre: ${emoji} — kom terug!`,
  // add to home screen
  installBtn: '📲 Sit Stapel op jou tuisskerm',
  installTipIos: 'Tik Deel ⬆️ en dan “Voeg by tuisskerm”',
  installDismiss: 'Nie nou nie',

  // --- Besoekers (visitors; js/game/visitors.js) ---
  visitors: 'Besoekers',                      // share line: "Weer: 💨 · Besoekers: 🐒🦹✋"
  visitorsToday: 'Besoekers vandag',          // menu, under the weather forecast
  monkeyBack: 'Ek sal terug wees!',          // Blouaap's speech bubble when a Perfek scares him off
  visitorFree: (name) => `${name} se skuld — jy hou jou hartjies ❤️`,   // a visitor knocked blocks into the sea
  thiefCaught: 'Gevang! Jy kry jou blokke terug.',
  thiefStole: (n) => (n === 1 ? 'Skelm Sakkie het 1 blok gesteel!' : `Skelm Sakkie het ${n} blokke gesteel!`),
  thiefEmpty: 'Skelm Sakkie het niks gekry nie!',
  gifts: 'Geskenke',                          // results grid label (🎁 cells)
  // one line on the results card about the day's visitors (never in the share text)
  resThiefCaught: 'Jy het Skelm Sakkie gevang! 👮',
  resThiefStole: (n) => (n === 1 ? 'Skelm Sakkie het 1 blok gesteel 🦹' : `Skelm Sakkie het ${n} blokke gesteel 🦹`),
  resThiefEmpty: 'Skelm Sakkie het met leë hande weggesluip 🦹',
  resMonkeyShooed: 'Jou Perfek het Blouaap weggejaag! 🐒',
  resMonkeyKnocked: (n) => (n === 1 ? 'Blouaap het 1 blok van jou toring afgegooi 🐒' : `Blouaap het ${n} blokke van jou toring afgegooi 🐒`),
  resMonkeyStood: 'Blouaap het gestamp, maar jou toring het bly staan! 🐒',
  resClownGift: (n) => (n > 1 ? `Hanswors het vir jou ${n} geskenke gebring 🎁` : 'Hanswors het vir jou ’n groot boomstam gebring 🪵'),
  clownFoundation: 'Nuwe fondament! 🪵 Alles daaronder staan vas',   // Hanswors's log sets as cement
  clownRewardTitle: (n) => `${n} Perfeks op ’n ry!`,
  clownRewardSub: 'Hanswors bring geskenke: ’n boomstam, en dalk ’n paar blokke. Bou daarop verder!',
  // first game only: the first visitor of each kind explains itself in its arrival banner (js/core/coach.js)
  coachMonkey: 'Land jou volgende blok Perfek, anders gooi Blouaap jou boonste blok in die see!',
  coachClown: 'Hanswors sit ’n groot boomstam (en dalk ’n paar geskenkblokke) bo-op jou toring en sement dit vas. Bou daarop verder!',
  coachThief: 'Tik vinnig op Skelm Sakkie, anders steel hy jou boonste blokke!',

  // --- Uitdagersreeks (head-to-head; docs/CHALLENGE-SPEC.md) ---
  duel: 'Uitdagersreeks',
  duelSub: 'Kop-aan-kop teen ’n ander speler',
  duelSubShort: 'Kop-aan-kop',            // under the menu button (beside Oefen)
  practiceSubShort: 'Dit tel nie',
  duelIntro: 'Julle bou kop-aan-kop met dieselfde blokke en weer. Wie eerste by ’n 10 m-merk kom, kies ’n straf vir die ander se toring. Eerste tot 50 m wen!',
  duelNick: 'Jou bynaam',
  duelNickHint: 'Wys vir jou teenstander (hoogstens 16 letters)',
  duelNickBad: 'Daardie naam gaan nie werk nie. Probeer ’n ander een.',
  duelNickSaved: 'Bynaam gestoor',
  duelRandom: 'Soek ’n teenstander',
  duelFriend: 'Daag ’n vriend uit',
  duelBot: 'Speel teen die rekenaar',
  duelRecord: (w, l) => `${w === 1 ? '1 oorwinning' : `${w} oorwinnings`} · ${l === 1 ? '1 nederlaag' : `${l} nederlae`}`,
  duelStreak: (n) => `${n} op ’n ry`,
  duelOffline: 'Lewendige wedstryde werk nog nie. Speel solank teen die rekenaar of daag ’n vriend uit met jou rondte.',
  duelSearchPractice: 'Oefen terwyl jy wag',
  duelPlayNow: 'Speel dadelik',
  duelPlayNowSub: 'teen ’n opname of Robot Rikus',
  duelSearchChip: 'Soek ’n teenstander…',
  duelSearchStop: 'Hou op soek',
  duelSearching: 'Soek ’n teenstander…',
  duelSearchHint: 'Ons soek iemand wat ook nou wil speel, so lank as wat dit vat. Bou solank ’n oefentoring, of speel dadelik.',
  duelNobody: 'Niemand is nou aanlyn nie. Jy speel teen ’n opname van ’n ander speler se wedstryd.',
  duelNobodyBot: 'Niemand is nou aanlyn nie. Jy speel teen Robot Rikus.',
  duelVs: (name) => `Teen ${name}!`,
  duelTheyCelebrate: (name) => `${name} vier!`,
  duelGo: 'Bou!',
  duelCancel: 'Kanselleer',
  duelReconnecting: 'Koppel weer aan…',
  duelWaitFriend: 'Wag vir jou vriend…',
  duelWaitHint: 'Stuur die skakel. Sodra jou vriend dit oopmaak, begin julle.',
  duelRoomText: (name, link, mode) => (mode === 'turns'
    ? `${name} daag jou uit vir Blok vir Blok op Stapel! Kom bou saam, om die beurt, aan een toring: ${link}`
    : `${name} daag jou uit vir ’n Stapel-wedstryd! Kom bou kop-aan-kop: ${link}`),
  duelPlayLater: 'Speel solank teen die rekenaar',
  duelFriendLater: 'Speel jou rondte teen Robot Rikus. Daarna stuur jy dit vir ’n vriend om te klop.',
  duelJoining: 'Koppel aan die uitdaging…',
  duelRoomGone: 'Hierdie uitdaging is verby of bestaan nie meer nie.',
  duelNoServer: 'Kon nie aan die bediener koppel nie. Probeer later weer.',
  duelBotName: 'Robot Rikus',
  duelSomeone: '’n Vriend',
  duelAttackIn: (name, visitor) => `${name} stuur ${visitor}!`,
  duelAttackOut: (visitor, name, emoji) => `Jy stuur ${visitor} na ${name}! ${emoji}`,
  duelChoose: (m, name) => `Eerste by ${m} m! Kies ’n straf vir ${name}:`,
  duelChooseLabel: 'Kies ’n straf',
  // --- Wedloop en Blok vir Blok (1.11): two ways to play the Uitdagersreeks ---
  duelIntroModes: 'Speel teen ’n ander speler, ’n vriend of Robot Rikus. Kies hoe:',
  modeChoose: 'Hoe wil julle speel?',
  modeRace: 'Wedloop',
  modeRaceTag: 'eerste tot 50 m wen',
  modeRaceWhat: 'Julle bou gelyktydig, elkeen sy eie toring met dieselfde blokke. Wie eerste by ’n 10 m-merk kom, kies ’n straf vir die ander. Eerste tot 50 m wen!',
  modeTurns: 'Blok vir Blok',
  modeTurnsTag: 'om die beurt op een toring',
  modeTurnsWhat: 'Een toring, om die beurt ’n blok. Val jou blok, of gooi jy blokke af, verloor jy ’n hartjie. Later kom rondtes: dieselfde weer of besoeker vir albei, een ná die ander. 5 Perfeks op ’n ry: kies ’n sabotasie vir die ander se volgende blok!',
  hudYou: 'Jy',
  turnsYourTurn: 'Jou beurt!',
  turnsTheirTurn: (name) => `${name} se beurt…`,
  turnsYouStart: 'Jy begin!',
  turnsTheyStart: (name) => `${name} begin.`,
  turnsLostHeart: (name) => `${name} verloor ’n hartjie!`,
  turnsYouLostHeart: 'Jy verloor ’n hartjie!',
  turnsChoose: (name) => `5 Perfeks op ’n ry! Kies ’n sabotasie vir ${name} se volgende blok:`,
  turnsChooseLabel: 'Kies ’n sabotasie',
  turnsSabotageOut: (what, name) => `${what} gaan na ${name} se volgende blok!`,
  turnsSabotageIn: (name, what) => `${name} stuur ${what} vir jou volgende blok!`,
  sabotageWhat: { fog: 'Sien skaars waar dit land', heat: 'Die hyskraan jaag', rain: 'Die blok gly' },
  turnsWhyTheyOut: (name) => `${name} se hartjies is op!`,
  turnsWhyYouOut: 'Jou hartjies is op.',
  turnsWhyTimeout: (name) => `${name} het te lank gevat.`,
  turnsWhyTurns: 'Die toring is klaar: die meeste hartjies wen.',
  turnsHeartsLeft: 'hartjies oor',
  turnsShareLine: (name, won) => `Blok vir Blok teen ${name}: ${won ? 'gewen! 🏆' : 'verloor'}`,
  turnsShareInvite: 'Kom speel Blok vir Blok teen my:',
  turnsBotNow: 'Speel solank teen Robot Rikus.',
  // Blok vir Blok rondtes (1.12): the same weather or visitor for both players, a turn each
  roundMineTitle: (what, first) => (first ? `${what}: jy eerste!` : `${what}: nou jy!`),
  roundTheirsTitle: (name, what) => `${name} kry ${what}`,
  roundTheirsSub: (first) => (first ? 'Jy kry netso een volgende.' : 'Net soos joune.'),
  roundVisitorHint: (type) => (type === 'thief' ? 'Tik hom vas voor hy steel: ’n hartjie terug!' : 'Gooi ’n Perfek, dan vlug hy: ’n hartjie terug!'),
  roundNext: (what) => `Volgende rondte: ${what} vir albei!`,
  roundStageSub: (k) => ['', 'Weer en besoekers: albei kry presies dieselfde.', 'Rukwinde, storms, hael en Skelm Sakkie!', 'Die rondtes kom vinniger. Hou vas!'][k] || '',
  roundBeatMine: (type, gain) => `${type === 'thief' ? 'Gevang!' : 'Blouaap vlug!'}${gain ? ' +❤️' : ''}`,
  roundBeatTheirs: (name, type, gain) => `${name} ${type === 'thief' ? 'vang Skelm Sakkie' : 'jaag Blouaap weg'}!${gain ? ' +❤️' : ''}`,
  roundThiefFirst: 'Vang eers Skelm Sakkie!',
  searchStoppedPause: 'Gestop met soek na ’n teenstander.',
  // "Nog 'n kans" (1.12): one more daily try for coins; the leaderboard keeps the better one, marked 🔁
  retryBtn: '🔁 Nog ’n kans',
  retryHow: 'Een keer per dag. Jou beste poging tel, met ’n 🔁 op die ranglys.',
  retryNeed: (n) => `Nog ${n} munte nodig (Oefen verdien munte).`,
  retryOnce: 'Jy het vandag se tweede kans klaar gebruik.',
  retryBought: 'Nog ’n kans! Jou beste poging tel.',
  retryPlay: 'Speel jou tweede kans',
  retryHead: '2de poging',
  retryMark: 'Tweede poging (Nog ’n kans)',
  emoteLabel: 'Stuur ’n emoji',
  emoteMute: 'Demp hul emoji’s',
  emoteUnmute: 'Wys hul emoji’s',
  emoteLimit: 'Genoeg emoji’s vir hierdie wedstryd',
  turnsNoRounds: (name) => `${name} se Stapel is ouer: hierdie wedstryd het geen rondtes nie.`,
  // height zones (1.12, js/core/zones.js): the first time a tower gets there
  zoneTitle: (k) => ['', 'Bo die wolke!', 'Hoog in die lug!', 'Ruimte se rand!', 'Die ruimte!', 'Tussen die sterre!'][k] || '',
  zoneSub: (k) => ['', '50 m: die stad is weg onder die wolke.', '100 m: hier vlieg die vliegtuie.', '200 m: jy sien die aarde se kurwe!', '300 m: welkom in die ruimte, ruimtevaarder!', '500 m: verby die maan. Legende!'][k] || '',
  playSomeoneNow: 'Speel nou teen iemand',
  raceLeadYou: 'Jy is voor! 💪',
  raceLeadThem: (name) => `${name} is voor jou! 😮`,
  // --- Muntstukke, kragte en rang (1.8; js/core/economy.js) ---
  coinsTotal: (n) => `jy het ${n}`,
  coinsCapped: 'genoeg vir vandag, kom môre weer',
  rankUp: (name) => `Nuwe rang: ${name}!`,
  powerups: 'Kragte',
  powerOn: 'AAN',
  shop: 'Winkel',
  shopPowerups: 'Kragte',
  shopLooks: 'Uitdager-styl',
  shopPowerupsNote: 'Vir Oefen. In die Daaglikse Toring kry almal ’n gratis Fondamentblok by 55 m.',
  shopLooksNote: 'Jou teenstander sien dit in die Uitdagersreeks. Dit maak jou nie sterker nie.',
  inBag: (n) => `In jou sak: ${n}`,
  buy: 'Koop',
  wear: 'Dra',
  wearing: 'Aan',
  preview: 'Wys',
  lockedRank: (rank) => `🔒 ${rank}-rang`,
  lockedWeek: '🔒 ’n Volle weekkis',
  // die weekkis (1.10, js/core/week.js)
  weekTitle: 'Weekkis',
  weekToday: (coins) => `Speel vandag: +${coins} 🪙`,
  weekTomorrow: (coins) => `Môre: +${coins} 🪙`,
  weekDay: (day) => `Dag ${day} van 7`,
  weekBox: (day, coins) => `📦 Dag ${day} van 7: +${coins} 🪙`,
  weekFull: 'Volle week! 🎉',
  weekSaved: (n) => (n > 1 ? `🛡️ ${n} Reeksskilde het jou week gered` : '🛡️ ’n Reeksskild het jou week gered'),
  weekRestart: 'Nuwe week: elke dag ’n groter kis',
  weekLook: (name) => `Nuwe titel: ${name}!`,
  weekShieldWon: '+1 Reeksskild 🛡️',
  weekShield: 'Reeksskild',
  weekShieldWhat: 'Mis jy ’n dag, hou dit jou weekkis se plek (jy kan 2 hê)',
  weekShieldHave: (n) => `Jy het ${n}`,
  lookKinds: { frame: 'Raam', badge: 'Wapen', title: 'Titel', celebration: 'Wen-viering', style: 'Straf-styl' },
  notEnoughCoins: 'Nie genoeg muntstukke nie. Speel nog ’n bietjie!',
  bought: (name) => `${name} gekoop!`,
  powerupSlow: 'Stadige hyskraan: 5 blokke lank 🐢',
  powerupShield: 'Skild aan! Die volgende aap of skelm bons af 🛡️',
  foundationSet: 'Nuwe fondament! 🧱 Alles daaronder staan vas',
  freeFoundation: 'Fondamentblok verdien! Tik 🧱 wanneer jy dit wil gebruik',
  shieldBlocked: (name) => `${name} bons van jou skild af! 🛡️`,
  resMonkeyBlocked: 'Jou skild het Blouaap gekeer! 🛡️',
  resThiefBlocked: 'Jou skild het Skelm Sakkie gekeer! 🛡️',
  rankPointsDelta: (d) => (d >= 0 ? `+${d} punte` : `${d} punte`),
  season: (month, year) => `Seisoen: ${month} ${year}`,
  rankPoints: (n) => (n === 1 ? '1 punt' : `${n} punte`),
  rankToNext: (n, rank) => `Nog ${n === 1 ? '1 punt' : `${n} punte`} tot ${rank}`,
  rankTop: 'Die hoogste rang! Hou dit so.',
  rankHow: (r) => `Wen teen ’n mens: +${r.win}% (meer teen ’n hoër rang). Verloor: −${r.loss}% (minder teen ’n hoër rang). Robot Rikus tel nie. Elke maand begin ’n nuwe seisoen: jou rang sak een vlak, en jy hou ’n kenteken vir jou beste.`,
  // (1.12) the ladder of 23 per mode (js/core/economy.js LADDER)
  rankDiv: ['I', 'II', 'III', 'Meester'],
  rankElite: { meesterbouer: 'Meesterbouer', grootmeester: 'Grootmeester', legende: 'Stapel-legende' },
  rankModeLabel: (mode) => (mode === 'turns' ? 'Blok vir Blok-rang' : 'Wedloop-rang'),
  rankPct: (toNext, next) => `Nog ${toNext}% tot ${next}`,
  rankPctDelta: (d) => (d >= 0 ? `+${d}%` : `${d}%`),
  rankDown: (name) => `Af na ${name}`,
  rankShield: (name) => `🛡️ Skild! Jy bly ${name}`,
  rankShieldOn: '🛡️ Skild aan: jou volgende verlies laat jou nie val nie.',
  rankPlacement: (n) => (n === 1 ? 'Nog 1 plasingswedstryd: ’n oorwinning tel 1,5 keer.' : `Nog ${n} plasingswedstryde: oorwinnings tel 1,5 keer.`),
  rankNotCounted: 'Teen Robot Rikus of ’n opname tel nie vir jou rang nie.',
  seasonBadges: 'Seisoenkentekens:',
  seasonReward: (rank, emoji) => `Nuwe seisoen! Jy hou ’n ${rank}-kenteken ${emoji}`,
  changeLook: 'Verander jou styl',
  duelGhostHit: (name, m) => `${name} se toring is ${m} m korter!`,
  duelYou: 'Jy',
  duelLeft: (name) => `${name} het die wedstryd verlaat.`,
  duelConnLost: 'Die verbinding het weggeval. Hierdie wedstryd tel nie.',
  // results
  duelWon: 'Jy het gewen!',
  duelLost: 'Jy het verloor',
  duelWhyGoal: 'Eerste tot 50 m!',
  duelWhyTheyGoal: (name) => `${name} was eerste by 50 m.`,
  duelWhyTheyFell: (name) => `${name} se toring het geval.`,
  duelWhyTheyLeft: (name) => `${name} het die wedstryd verlaat.`,
  duelWhyTheyQuit: (name) => `${name} het opgehou.`,
  duelWhyYouFell: 'Jou toring het eerste geval.',
  duelWhyYouQuit: 'Jy het opgehou.',
  duelAgain: 'Nog ’n wedstryd',
  duelShareHead: 'Stapel Uitdagersreeks ⚔️',
  duelShareLine: (you, name, them, won) => `Ek ${you} · ${name} ${them}: ${won ? 'gewen! 🏆' : 'verloor'}`,
  duelShareInvite: 'Kan jy my klop? Speel teen my rondte:',
  // somebody's run in a link (?teen=)
  duelLinkTitle: (name) => `${name} daag jou uit!`,
  duelLinkSub: (height) => `Bou dieselfde toring kop-aan-kop teen hul rondte (${height}).`,
  duelLinkPlay: 'Aanvaar die uitdaging',
  // --- Daaglikse ranglys (1.9.2; js/board.js) ---
  // the daily reminder (1.10, the Android app)
  remindTitle: 'Daaglikse herinnering',
  remindAsk: 'Moet ek jou elke dag herinner om jou toring te bou? Net een boodskap, en net as jy nog nie gebou het nie.',
  remindMorning: 'Oggend (08:00)',
  remindNoon: 'Middag (13:00)',
  remindEvening: 'Aand (18:30)',
  remindNo: 'Nee dankie',
  remindOff: 'Skakel af',
  remindButton: (t) => (t ? `Herinnering: ${t}` : 'Herinnering: af'),
  remindSet: (t) => `Ek herinner jou elke dag om ${t} 🔔`,
  remindDenied: 'Skakel kennisgewings vir Stapel aan in jou foon se instellings.',
  remind1: 'Vandag se toring wag! 🏗️',
  remind2: (day, coins) => `📦 Jou weekkis vir dag ${day} wag: +${coins} 🪙`,
  remind3: 'Blouaap wag vir jou… 🐒 Kom bou!',
  remind4: 'Hoe hoog kan jy vandag bou? 🔥',
  linkLater: 'Die uitdaging wag: bou eers jou toring klaar.',
  openInApp: 'Maak oop in die Stapel-app',
  versionNote: (v) => `Weergawe ${v}`,
  // the stages (config.js STAGES): announced when each begins
  stageTitle: (k) => ['', 'Moeiliker!', 'Nog moeiliker!', 'Op sy moeilikste!'][k] || '',
  stageSub: (k) => ['', 'Die weer begin draai, en daar kom besoekers.', 'Storms, hael en rukwinde. Pas op vir Skelm Sakkie!', 'Alles, en meer dikwels. Hou vas!'][k] || '',
  board: 'Ranglys',
  boardTitle: 'Vandag se ranglys',
  boardPlace: (rank, n) => `Jy is #${rank} van ${n} vandag`,
  boardEmpty: 'Nog niemand op die ranglys nie. Wees die eerste!',
  boardLoading: 'Laai die ranglys…',
  boardOffline: 'Die ranglys kan nie nou laai nie. Probeer later weer.',
  boardShowMe: 'Wys my op die ranglys',
  boardAs: (name) => `Jy verskyn as “${name}”. Verander jou bynaam in die Uitdagersreeks.`,
  boardYou: 'Jy',
  boardHiddenNote: 'Jy is versteek: ander sien jou nie, maar jy sien jou plek.',
  boardSaving: 'Stoor…',
  boardRetry: 'Nog nie gestoor nie: ons probeer weer sodra jy aanlyn is.',
  boardTitleYesterday: 'Gister se ranglys',
  // --- Taal (1.9; js/core/i18n.js) ---
  language: 'Taal',
  langPick: 'Kies jou taal · Choose your language',
  langNames: { af: 'Afrikaans', en: 'English' },
};

/** Weather display info. Keys match WEATHER_TYPES in config.js. */
export const WEATHER_INFO = {
  wind:    { emoji: '💨', name: 'Wind',        desc: (dir) => (dir < 0 ? 'Die wind waai na links ←' : 'Die wind waai na regs →') },
  gust:    { emoji: '🌪️', name: 'Warrelwind',  desc: () => 'Rukwinde van alle kante!' },
  rain:    { emoji: '🌧️', name: 'Reën',        desc: (dir) => (dir < 0 ? 'Glibberig! Blokke gly na links ←' : 'Glibberig! Blokke gly na regs →') },
  storm:   { emoji: '⛈️', name: 'Donderstorm', desc: () => 'Pasop vir die weerlig!' },
  hail:    { emoji: '🌨️', name: 'Hael',        desc: () => 'Haelkorrels tref jou toring!' },
  fog:     { emoji: '🌫️', name: 'Mis',         desc: () => 'Jy sien skaars waar die blok gaan land…' },
  heat:    { emoji: '☀️', name: 'Hittegolf',   desc: () => 'Die hyskraan jaag!' },
  rainbow: { emoji: '🌈', name: 'Reënboog',    desc: () => 'Dubbele punte vir elke Perfek!' },
};

/** Visitor display info (banner, share line, menu). Keys match VISITOR_TYPES in config.js. */
export const VISITOR_INFO = {
  monkey: { emoji: '🐒', name: 'Blouaap', hint: 'Land ’n Perfek, anders gooi hy blokke af!' },
  clown: { emoji: '🤡', name: 'Hanswors', hint: 'Geskenke: ’n boomstam en blokke om op te bou!' },
  thief: { emoji: '🦹', name: 'Skelm Sakkie', hint: 'Vang hom!' },
};

/** Uitdagersreeks punishments (the first to a height mark chooses one). Keys match DUEL.punishments. */
export const PUNISH_INFO = {
  monkey: { emoji: '🐒', name: 'Blouaap', what: 'Gooi blokke af' },
  thief: { emoji: '🦹', name: 'Skelm Sakkie', what: 'Steel blokke' },
  fog: { emoji: '🌫️', name: 'Mis', what: '3 blokke blind' },
  heat: { emoji: '☀️', name: 'Hittegolf', what: 'Hyskraan jaag' },
};
/** Power-ups (js/core/economy.js POWERUPS): Oefen, and the Daily Tower's free Fondamentblok. */
export const POWERUP_INFO = {
  foundation: { emoji: '🧱', name: 'Fondamentblok', what: 'Jou volgende blok is ’n lang sementblok: ’n nuwe fondament' },
  slow: { emoji: '🐢', name: 'Stadige hyskraan', what: 'Die hyskraan swaai stadiger vir 5 blokke' },
  shield: { emoji: '🛡️', name: 'Skild', what: 'Die volgende aap of skelm bons af' },
  heart: { emoji: '❤️', name: 'Ekstra hartjie', what: 'Kry een hartjie terug' },
};

/** Uitdagersreeks looks (js/core/economy.js COSMETICS): what an opponent sees of you. */
export const COSMETIC_INFO = {
  frame: {
    hout: { name: 'Hout' }, see: { name: 'See' }, goud: { name: 'Goud' }, springbok: { name: 'Groen en goud' },
    vuur: { name: 'Vuur' }, diamant: { name: 'Diamant' },
  },
  badge: {
    geen: { name: 'Geen' }, leeu: { name: 'Leeu' }, vuur: { name: 'Vuur' }, rugby: { name: 'Rugby' }, olifant: { name: 'Olifant' },
    arend: { name: 'Visarend' }, kroon: { name: 'Kroon' }, 's-brons': { name: 'Seisoen: Brons' }, 's-silwer': { name: 'Seisoen: Silwer' },
    's-goud': { name: 'Seisoen: Goud' }, 's-platinum': { name: 'Seisoen: Platinum' }, 's-diamant': { name: 'Seisoen: Diamant' },
  },
  title: {
    bouer: { name: 'Bouer' }, hyskraanheld: { name: 'Hyskraanheld' }, perfekmeester: { name: 'Perfek-meester' },
    wolkekrabber: { name: 'Wolkekrabber' }, toringkoning: { name: 'Toringkoning' }, getrou: { name: 'Getroue Bouer' },
  },
  celebration: {
    konfetti: { name: 'Konfetti' }, vuurwerk: { name: 'Vuurwerk' }, vuvuzela: { name: 'Vuvuzela' }, braai: { name: 'Braai' }, skrum: { name: 'Skrum' },
  },
  style: {
    gewoon: { name: 'Gewoon' }, pet: { name: 'Pet' }, sonbril: { name: 'Sonbril' }, hoed: { name: 'Hoed' }, kroon: { name: 'Kroon' },
  },
};

/** Duel ranks (js/core/economy.js RANKS). */
export const RANK_INFO = {
  brons: { name: 'Brons' }, silwer: { name: 'Silwer' }, goud: { name: 'Goud' }, platinum: { name: 'Platinum' }, diamant: { name: 'Diamant' },
};

/** Added after 🦹 in the share line when the player caught the thief. */
export const CAUGHT_EMOJI = '✋';
/** Added after a visitor the player's Skild (a power-up) kept off. */
export const SHIELD_EMOJI = '🛡️';

/** Afrikaans names for the block shapes (for the HUD "next" preview / how-to). */
export const SHAPE_NAMES = {
  plank: 'Plank',
  slab: 'Blad',
  brick: 'Baksteen',
  crate: 'Krat',
  cube: 'Blokkie',
  pillar: 'Pilaar',
  wedge: 'Wig',
  arch: 'U-blok',
  log: 'Boomstam',
  L: 'L-stuk',
  J: 'J-stuk',
  T: 'T-stuk',
};
