// English text for Stapel: the same keys and shapes as js/core/strings.js (tests/i18n.test.js checks
// that). js/core/i18n.js lays these over the Afrikaans tables when the player chooses English.
// Character names stay Afrikaans (Blouaap, Hanswors, Skelm Sakkie, Robot Rikus). Each Afrikaans saying
// has an English one (SAYINGS_EN). Use the typographic ’ (U+2019).

export const S_EN = {
  title: 'Stapel',
  tagline: 'Stack high. Stand strong.',
  loading: 'Loading…',
  rotate: 'Turn your phone upright to play.',

  // --- Menu ---
  daily: 'Daily Tower',
  dailyN: (n) => `Daily Tower #${n}`,
  playToday: 'Build today’s tower',
  doneToday: 'Done for today!',
  seeResult: 'See your result',
  nextTower: 'Next tower in',
  practice: 'Practice',
  practiceSub: 'Play as much as you like — it doesn’t count',
  howTo: 'How do I play?',
  howToShort: 'Rules',
  stats: 'Statistics',
  settings: 'Settings',
  sound: 'Sound',
  vibration: 'Vibration',
  on: 'On',
  off: 'Off',
  close: 'Close',
  back: 'Back',
  forecast: 'Today’s weather forecast',
  oneTry: 'one try, the same for everyone',
  todayLabel: 'Today:',
  sameForAll: 'The same blocks and weather for everyone. One try.',
  unfinished: 'Your last try was interrupted, but it counts as it stood.',
  newDay: 'A new tower is waiting!',

  // --- In the game ---
  tapToDrop: 'Tap to drop',
  perfect: 'Perfect!',
  perfectCombo: (n) => `Perfect ×${n}!`,
  good: 'Good',
  skew: 'Skew',
  lost: 'Oops!',
  extraLife: 'A heart back!',
  height: 'Height',
  points: 'Points',
  lives: 'Hearts',
  next: 'Next',
  combo: 'Combo',
  wobble: 'Wobble',
  waterBelow: (m) => `🌊 Flood line ${m} below`,
  waterRising: 'The water is rising!',
  waterDanger: 'Build faster — the water is coming!',
  waterRecede: 'The water is going down!',
  practiceLabel: 'Practice round',
  blocksLeft: (n) => (n === 1 ? '1 more block' : `${n} more blocks`),

  // --- Pause ---
  paused: 'Paused',
  resume: 'Keep playing',
  quit: 'Stop',
  quitWarnDaily: 'If you stop now, this try counts as your Daily Tower.',
  pause: 'Pause',

  // --- Results ---
  results: 'Result',
  overLives: 'Out of hearts!',
  overLivesSub: 'Too many blocks splashed into the sea.',
  overFlood: 'Flooded!',
  overFloodSub: 'The water caught up with your tower.',
  overQuit: 'Building stopped',
  overQuitSub: 'You switched off the crane.',
  blocks: 'Blocks',
  perfects: 'Perfect',
  bestCombo: 'Best combo',
  duration: 'Time',
  share: 'Share',
  shareWhatsApp: 'Share on WhatsApp',
  copy: 'Copy',
  copied: 'Copied!',
  copyFailed: 'Couldn’t copy',
  shared: 'Shared!',
  home: 'Home',
  practiceAgain: 'Practise again',
  newRecord: 'New record!',
  weatherToday: 'Weather',

  // --- Statistics ---
  played: 'Played',
  currentStreak: 'Current streak',
  maxStreak: 'Longest streak',
  bestHeight: 'Tallest tower',
  bestScore: 'Most points',
  totalPerfects: 'Perfect blocks',
  lastWeek: 'The last 7 days',
  noGamesYet: 'No Daily Towers built yet.',

  // --- How do I play? ---
  howToTitle: 'How do I play?',
  howToSteps: [
    { icon: '👆', text: 'Tap to drop the block. The white shape shows where it lands.' },
    { icon: '🎯', text: 'Land in the middle for a Perfect. Perfects in a row score extra.' },
    { icon: '🧱', text: 'Low down the tower sets like cement; up top it stays loose. The Balance meter shows how close the top is to toppling.' },
    { icon: '🌦️', text: 'The higher you build, the more weather: wind, rain, lightning, hail and fog.' },
    { icon: '🌊', text: 'The water rises. Keep your tower above the flood line.' },
    { icon: '❤️', text: 'Three hearts. A block in the sea costs one, every fourth Perfect brings one back.' },
    { icon: '🐒', text: 'Visitors: a Perfect chases Blouaap off, tap Skelm Sakkie to catch him, and Hanswors brings gifts. They never cost a heart.' },
    { icon: '🗓️', text: 'One Daily Tower a day: the same for everyone, one try. Practise as much as you like.' },
  ],
  lessonTry: 'Try the short lesson',
  lesson1: 'Tap anywhere to drop the block.',
  lesson2: 'Aim for the middle. The white shape shows where the block will land.',
  lesson3: 'Perfect! Five in a row bring Hanswors with gifts.',
  lesson3b: 'Close. The nearer the middle, the more points.',
  lesson4: 'The water rises. A block in the sea costs a heart.',
  lessonDone: 'You’re ready. Every day there’s one Daily Tower: the same blocks for everyone, and one try.',
  lessonDaily: 'Play today’s tower',
  lessonMore: 'Keep practising',
  lessonSkip: 'Skip',
  howToGo: 'Let’s build!',
  privacyPolicy: 'Privacy policy',

  // --- Share text (core/share.js) ---
  shareDailyHead: (n) => `Stapel #${n}`,
  sharePracticeHead: 'Stapel (practice round)',

  // --- First game: hints during play (js/core/coach.js) ---
  firstNudge: 'New? Just tap and play — we’ll show you how.',
  sayingOfDay: 'Saying of the day',
  coachTap: 'Tap to drop 👆',
  coachMiddle: 'Aim for the middle — the white outline shows where it lands',
  coachPerfect: 'Perfect! Do it again 🎯',
  coachWater: 'The water is rising — stay ahead of it 🌊',
  coachLost: 'A block in the sea costs a heart ❤️',

  // --- Added in 1.0.1 ---
  ghostHint: 'Your block lands here',
  clickToDrop: 'Click or press space to drop',
  nextTowerCaption: 'until the next tower',
  newTowerGo: 'Build the new tower',
  lostCount: 'Lost',
  notPlayed: 'not played',
  nothingToShare: 'Nothing to share — try again!',
  otherTab: 'You’re already building in another tab.',
  reloadNeeded: 'The screen froze. Reload the page if it doesn’t recover.',
  highContrast: 'Contrast',
  peek: 'Tower',
  peekBack: 'Result',
  wobbleTitle: 'Balance',

  // --- Sponsors ---
  adLabel: 'Advert',
  adOpens: 'opens in a new tab',
  advertiseHere: 'Advertise here',
  boardFree: 'Your advert here!',
  boardFreeSub: 'Advertise on Stapel',
  percentileBetter: (n) => `You did better than ${n}% of players today`,
  cityTitle: 'Your Stapel City',
  cityLine: (n) => (n === 1 ? 'Your city’s first tower is standing!' : `Your city now has ${n} towers!`),
  cityStreak: (n) => (n >= 2 ? `${n} days in a row` : ''),
  cityBest: 'Best tower',
  cityEmpty: 'Finish a Daily Tower to start building your city.',
  cityAria: (n, days) => `Your Stapel City: ${n} towers in the last ${days} days`,
  challengeMenu: (m) => `A friend challenges you: beat ${m}! 🚩`,
  challengeLine: (m) => `Beat this: ${m}`,
  challengeWon: 'You beat your friend! 🎉',
  tomorrow: 'Tomorrow',
  tomorrowLine: (emoji) => `Tomorrow: ${emoji} — come back!`,
  installBtn: '📲 Put Stapel on your home screen',
  installTipIos: 'Tap Share ⬆️ and then “Add to Home Screen”',
  installDismiss: 'Not now',

  // --- Visitors (js/game/visitors.js) ---
  visitors: 'Visitors',
  visitorsToday: 'Visitors today',
  monkeyBack: 'I’ll be back!',
  visitorFree: (name) => `${name}’s fault — you keep your hearts ❤️`,
  thiefCaught: 'Caught! You get your blocks back.',
  thiefStole: (n) => (n === 1 ? 'Skelm Sakkie stole 1 block!' : `Skelm Sakkie stole ${n} blocks!`),
  thiefEmpty: 'Skelm Sakkie got nothing!',
  gifts: 'Gifts',
  resThiefCaught: 'You caught Skelm Sakkie! 👮',
  resThiefStole: (n) => (n === 1 ? 'Skelm Sakkie stole 1 block 🦹' : `Skelm Sakkie stole ${n} blocks 🦹`),
  resThiefEmpty: 'Skelm Sakkie sneaked off empty-handed 🦹',
  resMonkeyShooed: 'Your Perfect chased Blouaap away! 🐒',
  resMonkeyKnocked: (n) => (n === 1 ? 'Blouaap threw 1 block off your tower 🐒' : `Blouaap threw ${n} blocks off your tower 🐒`),
  resMonkeyStood: 'Blouaap stamped, but your tower stood firm! 🐒',
  resClownGift: (n) => (n > 1 ? `Hanswors brought you ${n} gifts 🎁` : 'Hanswors brought you a big log 🪵'),
  clownFoundation: 'New foundation! 🪵 Everything under it is set',
  clownRewardTitle: (n) => `${n} Perfects in a row!`,
  clownRewardSub: 'Hanswors brings gifts: a log, and maybe a few blocks. Build on top of it!',
  coachMonkey: 'Land your next block Perfect, or Blouaap throws your top block into the sea!',
  coachClown: 'Hanswors lays a big log (and maybe a few gift blocks) on your tower and cements it in. Build on top of it!',
  coachThief: 'Tap Skelm Sakkie quickly, or he steals your top blocks!',

  // --- Challenger Series (Uitdagersreeks) ---
  duel: 'Challenger Series',
  duelSub: 'Head-to-head against another player',
  duelSubShort: 'Head-to-head',
  practiceSubShort: 'Doesn’t count',
  duelIntro: 'You build head-to-head with the same blocks and weather. Whoever reaches a 10 m mark first picks a punishment for the other tower. First to 50 m wins!',
  duelNick: 'Your nickname',
  duelNickHint: 'Shown to your opponent (16 letters at most)',
  duelNickBad: 'That name won’t work. Try another one.',
  duelNickSaved: 'Nickname saved',
  duelRandom: 'Find an opponent',
  duelFriend: 'Challenge a friend',
  duelBot: 'Play the computer',
  duelRecord: (w, l) => `${w === 1 ? '1 win' : `${w} wins`} · ${l === 1 ? '1 loss' : `${l} losses`}`,
  duelStreak: (n) => `${n} in a row`,
  duelOffline: 'Live matches don’t work yet. Play the computer for now, or challenge a friend with your round.',
  duelSearchPractice: 'Practise while you wait',
  duelPlayNow: 'Play right away',
  duelPlayNowSub: 'against a recording or Robot Rikus',
  duelSearchChip: 'Looking for an opponent…',
  duelSearchStop: 'Stop looking',
  duelSearching: 'Finding an opponent…',
  duelSearchHint: 'We’re looking for someone who wants to play right now, for as long as it takes. Build a practice tower meanwhile, or play right away.',
  duelNobody: 'Nobody’s online right now. You’re playing a recording of another player’s match.',
  duelNobodyBot: 'Nobody’s online right now. You’re playing Robot Rikus.',
  duelVs: (name) => `vs ${name}!`,
  duelTheyCelebrate: (name) => `${name} celebrates!`,
  duelGo: 'Build!',
  duelCancel: 'Cancel',
  duelReconnecting: 'Reconnecting…',
  duelWaitFriend: 'Waiting for your friend…',
  duelWaitHint: 'Send the link. As soon as your friend opens it, you start.',
  duelRoomText: (name, link, mode) => (mode === 'turns'
    ? `${name} challenges you to Block by Block on Stapel! Come build one tower together, taking turns: ${link}`
    : `${name} challenges you to a Stapel match! Come build head-to-head: ${link}`),
  duelPlayLater: 'Play the computer meanwhile',
  duelFriendLater: 'Play your round against Robot Rikus. Then send it to a friend to beat.',
  duelJoining: 'Joining the challenge…',
  duelRoomGone: 'This challenge is over or no longer exists.',
  duelNoServer: 'Couldn’t connect to the server. Try again later.',
  duelBotName: 'Robot Rikus',
  duelSomeone: 'Your friend',
  duelAttackIn: (name, visitor) => `${name} sends ${visitor}!`,
  duelAttackOut: (visitor, name, emoji) => `You send ${visitor} to ${name}! ${emoji}`,
  duelChoose: (m, name) => `First to ${m} m! Pick a punishment for ${name}:`,
  duelChooseLabel: 'Pick a punishment',
  duelIntroModes: 'Play another player, a friend or Robot Rikus. Choose how:',
  modeChoose: 'How do you want to play?',
  modeRace: 'Race',
  modeRaceTag: 'first to 50 m wins',
  modeRaceWhat: 'You build at the same time, each your own tower with the same blocks. Whoever reaches a 10 m mark first picks a punishment for the other. First to 50 m wins!',
  modeTurns: 'Block by Block',
  modeTurnsTag: 'taking turns on one tower',
  modeTurnsWhat: 'One tower, a block each in turn. Drop your block, or knock blocks off, and you lose a heart. Then come rounds: the same weather or visitor for both of you, one after the other. 5 Perfects in a row: pick a sabotage for their next block!',
  hudYou: 'You',
  turnsYourTurn: 'Your turn!',
  turnsTheirTurn: (name) => `${name}’s turn…`,
  turnsYouStart: 'You start!',
  turnsTheyStart: (name) => `${name} starts.`,
  turnsLostHeart: (name) => `${name} loses a heart!`,
  turnsYouLostHeart: 'You lose a heart!',
  turnsChoose: (name) => `5 Perfects in a row! Pick a sabotage for ${name}’s next block:`,
  turnsChooseLabel: 'Pick a sabotage',
  turnsSabotageOut: (what, name) => `${what} goes to ${name}’s next block!`,
  turnsSabotageIn: (name, what) => `${name} sends ${what} for your next block!`,
  sabotageWhat: { fog: 'Hard to see where it lands', heat: 'The crane races', rain: 'The block slides' },
  turnsWhyTheyOut: (name) => `${name} is out of hearts!`,
  turnsWhyYouOut: 'You’re out of hearts.',
  turnsWhyTimeout: (name) => `${name} took too long.`,
  turnsWhyTurns: 'The tower is done: the most hearts win.',
  turnsHeartsLeft: 'hearts left',
  turnsShareLine: (name, won) => `Block by Block against ${name}: ${won ? 'won! 🏆' : 'lost'}`,
  turnsShareInvite: 'Come play Block by Block against me:',
  turnsBotNow: 'Play Robot Rikus for now.',
  roundMineTitle: (what, first) => (first ? `${what}: you first!` : `${what}: your turn!`),
  roundTheirsTitle: (name, what) => `${name} gets ${what}`,
  roundTheirsSub: (first) => (first ? 'You get the same one next.' : 'Same as yours.'),
  roundVisitorHint: (type) => (type === 'thief' ? 'Tap him before he steals: a heart back!' : 'Drop a Perfect and he runs: a heart back!'),
  roundNext: (what) => `Next round: ${what} for both!`,
  roundStageSub: (k) => ['', 'Weather and visitors: you both get exactly the same.', 'Gusts, storms, hail and Skelm Sakkie!', 'The rounds come faster. Hold on!'][k] || '',
  roundBeatMine: (type, gain) => `${type === 'thief' ? 'Caught!' : 'Blouaap runs!'}${gain ? ' +❤️' : ''}`,
  roundBeatTheirs: (name, type, gain) => `${name} ${type === 'thief' ? 'catches Skelm Sakkie' : 'chases Blouaap off'}!${gain ? ' +❤️' : ''}`,
  roundThiefFirst: 'Catch Skelm Sakkie first!',
  searchStoppedPause: 'Stopped looking for an opponent.',
  retryBtn: '🔁 One more try',
  retryHow: 'Once a day. Your best try counts, with a 🔁 on the leaderboard.',
  retryNeed: (n) => `${n} more coins needed (Practice earns coins).`,
  retryOnce: 'You’ve used today’s second try.',
  retryBought: 'One more try! Your best try counts.',
  retryPlay: 'Play your second try',
  retryHead: '2nd try',
  retryMark: 'Second try (One more try)',
  emoteLabel: 'Send an emoji',
  emoteMute: 'Mute their emojis',
  emoteUnmute: 'Show their emojis',
  emoteLimit: 'That’s enough emojis for this match',
  turnsNoRounds: (name) => `${name}'s Stapel is older: no rounds in this match.`,
  zoneTitle: (k) => ['', 'Above the clouds!', 'High in the sky!', 'Edge of space!', 'Outer space!', 'Among the stars!'][k] || '',
  zoneSub: (k) => ['', '50 m: the city is gone below the clouds.', '100 m: this is where the planes fly.', '200 m: you can see the curve of the Earth!', '300 m: welcome to space, astronaut!', '500 m: past the moon. Legend!'][k] || '',
  playSomeoneNow: 'Play someone now',
  raceLeadYou: 'You’re ahead! 💪',
  raceLeadThem: (name) => `${name} is ahead of you! 😮`,
  // --- Coins, power-ups and rank (1.8; js/core/economy.js) ---
  coinsTotal: (n) => `you have ${n}`,
  coinsCapped: 'enough for today, come back tomorrow',
  rankUp: (name) => `New rank: ${name}!`,
  powerups: 'Power-ups',
  powerOn: 'ON',
  shop: 'Shop',
  shopPowerups: 'Power-ups',
  shopLooks: 'Challenger style',
  shopPowerupsNote: 'For Practice. In the Daily Tower everyone gets a free Foundation block at 55 m.',
  shopLooksNote: 'Your opponent sees this in the Challenger Series. It doesn’t make you stronger.',
  inBag: (n) => `In your bag: ${n}`,
  buy: 'Buy',
  wear: 'Wear',
  wearing: 'Wearing',
  preview: 'Try it',
  lockedRank: (rank) => `🔒 ${rank} rank`,
  lockedWeek: '🔒 A full week chest',
  weekTitle: 'Week chest',
  weekToday: (coins) => `Play today: +${coins} 🪙`,
  weekTomorrow: (coins) => `Tomorrow: +${coins} 🪙`,
  weekDay: (day) => `Day ${day} of 7`,
  weekBox: (day, coins) => `📦 Day ${day} of 7: +${coins} 🪙`,
  weekFull: 'Full week! 🎉',
  weekSaved: (n) => (n > 1 ? `🛡️ ${n} streak shields saved your week` : '🛡️ A streak shield saved your week'),
  weekRestart: 'A new week: a bigger box every day',
  weekLook: (name) => `New title: ${name}!`,
  weekShieldWon: '+1 streak shield 🛡️',
  weekShield: 'Streak shield',
  weekShieldWhat: 'Miss a day and it keeps your place in the week chest (you can hold 2)',
  weekShieldHave: (n) => `You have ${n}`,
  lookKinds: { frame: 'Frame', badge: 'Badge', title: 'Title', celebration: 'Win celebration', style: 'Punishment style' },
  notEnoughCoins: 'Not enough coins. Play a little more!',
  bought: (name) => `${name} bought!`,
  powerupSlow: 'Slow crane for 5 blocks 🐢',
  powerupShield: 'Shield on! The next monkey or thief bounces off 🛡️',
  foundationSet: 'New foundation! 🧱 Everything under it is set',
  freeFoundation: 'Foundation block earned! Tap 🧱 when you want to use it',
  shieldBlocked: (name) => `${name} bounces off your shield! 🛡️`,
  resMonkeyBlocked: 'Your shield stopped Blouaap! 🛡️',
  resThiefBlocked: 'Your shield stopped Skelm Sakkie! 🛡️',
  rankPointsDelta: (d) => (d >= 0 ? `+${d} points` : `${d} points`),
  season: (month, year) => `Season: ${month} ${year}`,
  rankPoints: (n) => (n === 1 ? '1 point' : `${n} points`),
  rankToNext: (n, rank) => `${n === 1 ? '1 point' : `${n} points`} to ${rank}`,
  rankTop: 'The highest rank! Keep it up.',
  rankHow: (r) => `Win against a person: +${r.win}% (more against a higher rank). Lose: −${r.loss}% (less against a higher rank). Robot Rikus doesn't count. Every month a new season starts: your rank drops one tier, and you keep a badge for your best.`,
  rankDiv: ['I', 'II', 'III', 'Master'],
  rankElite: { meesterbouer: 'Master Builder', grootmeester: 'Grandmaster', legende: 'Stapel Legend' },
  rankModeLabel: (mode) => (mode === 'turns' ? 'Block by Block rank' : 'Race rank'),
  rankPct: (toNext, next) => `${toNext}% to ${next}`,
  rankPctDelta: (d) => (d >= 0 ? `+${d}%` : `${d}%`),
  rankDown: (name) => `Down to ${name}`,
  rankShield: (name) => `🛡️ Shield! You stay ${name}`,
  rankShieldOn: '🛡️ Shield on: your next loss won’t drop you.',
  rankPlacement: (n) => (n === 1 ? '1 placement match left: a win counts 1.5x.' : `${n} placement matches left: wins count 1.5x.`),
  rankNotCounted: 'Matches against Robot Rikus or a recording don’t count for your rank.',
  seasonBadges: 'Season badges:',
  seasonReward: (rank, emoji) => `New season! You keep a ${rank} badge ${emoji}`,
  changeLook: 'Change your style',
  duelGhostHit: (name, m) => `${name}’s tower is ${m} m shorter!`,
  duelYou: 'You',
  duelLeft: (name) => `${name} left the match.`,
  duelConnLost: 'The connection dropped. This match doesn’t count.',
  // results
  duelWon: 'You won!',
  duelLost: 'You lost',
  duelWhyGoal: 'First to 50 m!',
  duelWhyTheyGoal: (name) => `${name} was first to 50 m.`,
  duelWhyTheyFell: (name) => `${name}’s tower fell.`,
  duelWhyTheyLeft: (name) => `${name} left the match.`,
  duelWhyTheyQuit: (name) => `${name} stopped.`,
  duelWhyYouFell: 'Your tower fell first.',
  duelWhyYouQuit: 'You stopped.',
  duelAgain: 'Another match',
  duelShareHead: 'Stapel Challenger Series ⚔️',
  duelShareLine: (you, name, them, won) => `Me ${you} · ${name} ${them}: ${won ? 'won! 🏆' : 'lost'}`,
  duelShareInvite: 'Can you beat me? Play against my round:',
  // somebody's run in a link (?teen=)
  duelLinkTitle: (name) => `${name} challenges you!`,
  duelLinkSub: (height) => `Build the same tower head-to-head against their round (${height}).`,
  duelLinkPlay: 'Accept the challenge',
  // --- Daily leaderboard (1.9.2; js/board.js) ---
  remindTitle: 'Daily reminder',
  remindAsk: 'Shall I remind you every day to build your tower? Just one message, and only if you haven’t built yet.',
  remindMorning: 'Morning (08:00)',
  remindNoon: 'Midday (13:00)',
  remindEvening: 'Evening (18:30)',
  remindNo: 'No thanks',
  remindOff: 'Switch off',
  remindButton: (t) => (t ? `Reminder: ${t}` : 'Reminder: off'),
  remindSet: (t) => `I’ll remind you every day at ${t} 🔔`,
  remindDenied: 'Turn on notifications for Stapel in your phone’s settings.',
  remind1: 'Today’s tower is waiting! 🏗️',
  remind2: (day, coins) => `📦 Your week chest for day ${day} is waiting: +${coins} 🪙`,
  remind3: 'Blouaap is waiting for you… 🐒 Come build!',
  remind4: 'How high can you build today? 🔥',
  linkLater: 'The challenge is waiting: finish your tower first.',
  openInApp: 'Open in the Stapel app',
  versionNote: (v) => `Version ${v}`,
  stageTitle: (k) => ['', 'Tougher!', 'Even tougher!', 'Toughest!'][k] || '',
  stageSub: (k) => ['', 'The weather turns, and visitors drop by.', 'Storms, hail and gusts. Watch out for Skelm Sakkie!', 'Everything, and more often. Hold on!'][k] || '',
  board: 'Leaderboard',
  boardTitle: 'Today’s leaderboard',
  boardPlace: (rank, n) => `You’re #${rank} of ${n} today`,
  boardEmpty: 'Nobody on the leaderboard yet. Be the first!',
  boardLoading: 'Loading the leaderboard…',
  boardOffline: 'The leaderboard can’t load right now. Try again later.',
  boardShowMe: 'Show me on the leaderboard',
  boardAs: (name) => `You appear as “${name}”. Change your nickname in the Challenger Series.`,
  boardYou: 'You',
  boardHiddenNote: 'You’re hidden: others don’t see you, but you see your place.',
  boardSaving: 'Saving…',
  boardRetry: 'Not saved yet: we’ll try again once you’re online.',
  boardTitleYesterday: 'Yesterday’s leaderboard',
  // --- Language (1.9) ---
  language: 'Language',
  langPick: 'Kies jou taal · Choose your language',
  langNames: { af: 'Afrikaans', en: 'English' },
};

export const WEATHER_INFO_EN = {
  wind: { name: 'Wind', desc: (dir) => (dir < 0 ? 'The wind blows to the left ←' : 'The wind blows to the right →') },
  gust: { name: 'Whirlwind', desc: () => 'Gusts from every side!' },
  rain: { name: 'Rain', desc: (dir) => (dir < 0 ? 'Slippery! Blocks slide to the left ←' : 'Slippery! Blocks slide to the right →') },
  storm: { name: 'Thunderstorm', desc: () => 'Watch out for the lightning!' },
  hail: { name: 'Hail', desc: () => 'Hailstones hit your tower!' },
  fog: { name: 'Fog', desc: () => 'You can barely see where the block will land…' },
  heat: { name: 'Heat wave', desc: () => 'The crane speeds up!' },
  rainbow: { name: 'Rainbow', desc: () => 'Double points for every Perfect!' },
};

export const VISITOR_INFO_EN = {
  monkey: { name: 'Blouaap', hint: 'Land a Perfect, or he throws blocks off!' },
  clown: { name: 'Hanswors', hint: 'Gifts: a log and blocks to build on!' },
  thief: { name: 'Skelm Sakkie', hint: 'Catch him!' },
};

export const PUNISH_INFO_EN = {
  monkey: { name: 'Blouaap', what: 'Throws blocks off' },
  thief: { name: 'Skelm Sakkie', what: 'Steals blocks' },
  fog: { name: 'Fog', what: 'Blind for 3 blocks' },
  heat: { name: 'Heat wave', what: 'Crane speeds up' },
};

export const POWERUP_INFO_EN = {
  foundation: { name: 'Foundation block', what: 'Your next block is a long cement slab: a new foundation' },
  slow: { name: 'Slow crane', what: 'The crane swings slower for 5 blocks' },
  shield: { name: 'Shield', what: 'The next monkey or thief bounces off' },
  heart: { name: 'Extra heart', what: 'Get one heart back' },
};

export const COSMETIC_INFO_EN = {
  frame: {
    hout: { name: 'Wood' }, see: { name: 'Sea' }, goud: { name: 'Gold' }, springbok: { name: 'Green and gold' },
    vuur: { name: 'Fire' }, diamant: { name: 'Diamond' },
  },
  badge: {
    geen: { name: 'None' }, leeu: { name: 'Lion' }, vuur: { name: 'Fire' }, rugby: { name: 'Rugby' }, olifant: { name: 'Elephant' },
    arend: { name: 'Fish eagle' }, kroon: { name: 'Crown' }, 's-brons': { name: 'Season: Bronze' }, 's-silwer': { name: 'Season: Silver' },
    's-goud': { name: 'Season: Gold' }, 's-platinum': { name: 'Season: Platinum' }, 's-diamant': { name: 'Season: Diamond' },
  },
  title: {
    bouer: { name: 'Builder' }, hyskraanheld: { name: 'Crane hero' }, perfekmeester: { name: 'Perfect master' },
    wolkekrabber: { name: 'Skyscraper' }, toringkoning: { name: 'Tower king' }, getrou: { name: 'Loyal Builder' },
  },
  celebration: {
    konfetti: { name: 'Confetti' }, vuurwerk: { name: 'Fireworks' }, vuvuzela: { name: 'Vuvuzela' }, braai: { name: 'Braai' }, skrum: { name: 'Scrum' },
  },
  style: {
    gewoon: { name: 'Plain' }, pet: { name: 'Cap' }, sonbril: { name: 'Sunglasses' }, hoed: { name: 'Top hat' }, kroon: { name: 'Crown' },
  },
};

export const RANK_INFO_EN = {
  brons: { name: 'Bronze' }, silwer: { name: 'Silver' }, goud: { name: 'Gold' }, platinum: { name: 'Platinum' }, diamant: { name: 'Diamond' },
};

export const SHAPE_NAMES_EN = {
  plank: 'Plank',
  slab: 'Slab',
  brick: 'Brick',
  crate: 'Crate',
  cube: 'Cube',
  pillar: 'Pillar',
  wedge: 'Wedge',
  arch: 'U-block',
  log: 'Log',
  L: 'L-piece',
  J: 'J-piece',
  T: 'T-piece',
};

/**
 * The English saying shown in place of each Afrikaans one (js/core/sayings.js): the closest real English
 * saying where there is one, else the plain meaning. Keyed by the Afrikaans line, so English players get
 * the same saying of the day as everyone else.
 */
export const SAYINGS_EN = {
  'Aanhouer wen.': 'Perseverance pays off.',
  'Aanhouer wen!': 'Perseverance pays off!',
  'Klein begin, aanhou wen.': 'Little by little, one goes far.',
  'Klein begin, aanhou wen!': 'Little by little, one goes far!',
  'Rome is nie in een dag gebou nie.': 'Rome wasn’t built in a day.',
  '’n Boer maak ’n plan.': 'Necessity is the mother of invention.',
  '’n Boer maak ’n plan!': 'Where there’s a will, there’s a way!',
  'Alle begin is moeilik.': 'All beginnings are hard.',
  'Oefening baar kuns.': 'Practice makes perfect.',
  'Waar daar ’n wil is, is daar ’n weg.': 'Where there’s a will, there’s a way.',
  'Wie nie waag nie, wen nie.': 'Nothing ventured, nothing gained.',
  'Moed verloor, alles verloor.': 'Never lose heart.',
  'Moed verloor, alles verloor — probeer weer!': 'Never lose heart — try again!',
  'Na reën kom sonskyn.': 'Every cloud has a silver lining.',
  'Moenie die bobbejaan agter die bult gaan haal nie.': 'Don’t cross a bridge before you come to it.',
  'Môre is nog ’n dag.': 'Tomorrow is another day.',
  'Elke hond kry sy dag.': 'Every dog has its day.',
  'Hou die blink kant bo.': 'Look on the bright side.',
  'Hou die blink kant bo!': 'Look on the bright side!',
  'Agteros kom ook in die kraal.': 'Slow and steady wins the race.',
  'Wie laaste lag, lag die lekkerste.': 'Whoever laughs last laughs best.',
  'Hoe meer haas, hoe minder spoed.': 'More haste, less speed.',
  'Haastige spoed is selde goed.': 'Haste makes waste.',
  'Eendrag maak mag.': 'Unity is strength.',
  'Een swaeltjie maak nie ’n somer nie.': 'One swallow doesn’t make a summer.',
  'Die beste stuurlui staan aan wal.': 'Everyone’s an expert from the sidelines.',
  'Kyk eers hoe die kat uit die boom klim.': 'Wait and see which way the wind blows.',
  'Beter laat as nooit.': 'Better late than never.',
  'Stadig oor die klippe.': 'Easy does it.',
  'So sterk soos ’n os!': 'As strong as an ox!',
  'Stapel hoog, staan sterk!': 'Stack high, stand strong!',
  'Klein maar dapper!': 'Small but mighty!',
  'Dit staan soos ’n paal bo water!': 'No doubt about it!',
  'Jy is nie onder ’n kalkoen uitgebroei nie!': 'You weren’t born yesterday!',
  'Gedane sake het geen keer nie.': 'No use crying over spilt milk.',
  'Dis die laaste strooi wat die kameel se rug breek.': 'It’s the last straw that breaks the camel’s back.',
  'Vroeg ryp, vroeg vrot.': 'Early ripe, early rotten.',
  '’n Halwe eier is beter as ’n leë dop.': 'Half a loaf is better than none.',
  'Iets is beter as niks.': 'Something is better than nothing.',
};
